---
title: "Character&Bacteria"
output: html_document
date: "2024-12-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE}
library(tidyverse)
library(ggforce)
library(ggprism)
library(stringr)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggrepel)
```

```{r snp_gene}
#导入SNP位点和确定名称的基因
Bj_snp_gene0<-read.csv("data.12.16/bac_age_BJ_snp.csv")
df<-Bj_snp_gene0[,c(1,3,4)]
df <- df %>% mutate(across(where(is.character), ~na_if(., "")))
df1 <- na.omit(df)
```

```{r snp_bac}
#导入SNP、BONF和对应菌群
Bj_snp_bac0<-read.csv("plot12.01/bac_age_BJ_rel.csv")
df2<-Bj_snp_bac0[,c(2,5,11)]
```


```{r snp_bac+gene}
#合并SNP、BONF、Bacteria、external_name、去除NA
df1
df2
merged_df <- merge(df2, df1[, c("SNP", "external_name", "gene_id")], by = "SNP", all.x = TRUE)
merged_df
merged_df_clean <- merged_df[!duplicated(merged_df), ]
merged_df_clean
merged_df_clean <- na.omit(merged_df_clean)
df3<-merged_df_clean
```

```{r Moisture1}
bac<-unique(df3$Bacteria)
bac
cha<-read.csv(file = "data.11.08/manifestotype.csv")
cha_bac<-read.csv(file = "data.11.08/Beijing.csv")
cha
bj_index <- grepl("^BJ",cha$Sample.id)
 
# 使用逻辑索引来提取符合条件的行
bj_df <- cha[bj_index, ]
      
 m<-as.numeric(bj_df[,4])
mean_value <- mean(m)

# 单样本t检验，检验数据集的平均值是否显著不同于0
t_test_result <- t.test(m, mu = 0)

# 打印t检验结果
print(t_test_result)

# 计算每个值与平均值的Z分数
z_scores <- (m - mean_value) / sd(m)

# 确定显著性阈值，这里使用0.1的显著性水平
alpha <- 0.1
critical_z <- qnorm(1 - alpha/2)  # 双尾检验

# 找出Z分数大于临界Z值的数据点，即显著大于平均值的数据点
significant_values <- m[z_scores > critical_z]

# 打印显著大于平均值的数据点
print(paste("显著大于平均值的数据点：", significant_values))
#取显著性水平0.1
```


```{r Moisture2}
significant_values
m_S <-bj_df %>% filter(Moisture %in% as.character(significant_values))
name<-m_S[,1]
cha_bac_clean<- cha_bac  %>% filter(Species %in% bac)
cha_bac_clean
# 假设significant_values是一个包含列名的向量
m_name_bac <- cha_bac_clean %>% select(Species,all_of(name))
m_name_bac
#对这6个人的结果求平均相对丰度，降序排序，取前10种？
mean_m <- m_name_bac %>%mutate(.,mean=rowMeans(m_name_bac[,-1])) %>% arrange(desc(mean))
mean_m
m_bac<- mean_m %>% filter(mean>0.005)
Moisture<-data.frame(Character="Moisture",Bacteria=m_bac[,1])
Moisture
```

```{r Gloss1}
 g<-as.numeric(bj_df[,5])
mean_value <- mean(g)

# 单样本t检验，检验数据集的平均值是否显著不同于0
t_test_result <- t.test(g, mu = 0)

# 打印t检验结果
print(t_test_result)

# 计算每个值与平均值的Z分数
z_scores <- (g - mean_value) / sd(g)

# 确定显著性阈值，这里使用0.1的显著性水平
alpha <- 0.1
critical_z <- qnorm(1 - alpha/2)  # 双尾检验

# 找出Z分数大于临界Z值的数据点，即显著大于平均值的数据点
significant_values <- g[z_scores > critical_z]

# 打印显著大于平均值的数据点
print(paste("显著大于平均值的数据点：", significant_values))
#取显著性水平0.1
```


```{r Gloss2}
significant_values
g_S <-bj_df %>% filter(Gloss %in% as.character(significant_values))
name<-g_S[,1]
cha_bac_clean<- cha_bac  %>% filter(Species %in% bac)
cha_bac_clean
# 假设significant_values是一个包含列名的向量
g_name_bac <- cha_bac_clean %>% select(Species,all_of(name))
g_name_bac
#对这6个人的结果求平均相对丰度，降序排序，取前10种？
mean_g <- g_name_bac %>%mutate(.,mean=rowMeans(g_name_bac[,-1])) %>% arrange(desc(mean))
mean_g
g_bac<- mean_g %>% filter(mean>0.005)
Gloss<-data.frame(Character="Gloss",Bacteria=g_bac[,1])
Gloss
```


```{r Sebum1}
 s<-as.numeric(bj_df[,6])
mean_value <- mean(s)

# 单样本t检验，检验数据集的平均值是否显著不同于0
t_test_result <- t.test(s, mu = 0)

# 打印t检验结果
print(t_test_result)

# 计算每个值与平均值的Z分数
z_scores <- (s - mean_value) / sd(s)

# 确定显著性阈值，这里使用0.1的显著性水平
alpha <- 0.1
critical_z <- qnorm(1 - alpha/2)  # 双尾检验

# 找出Z分数大于临界Z值的数据点，即显著大于平均值的数据点
significant_values <- s[z_scores > critical_z]

# 打印显著大于平均值的数据点
print(paste("显著大于平均值的数据点：", significant_values))
#取显著性水平0.1
```


```{r Sebum2}
significant_values
s_S <-bj_df %>% filter(Sebum %in% as.character(significant_values))
name<-s_S[,1]
cha_bac_clean<- cha_bac  %>% filter(Species %in% bac)
cha_bac_clean
# 假设significant_values是一个包含列名的向量
s_name_bac <- cha_bac_clean %>% select(Species,all_of(name))
s_name_bac
#对这6个人的结果求平均相对丰度，降序排序，取前10种？
mean_s <- s_name_bac %>%mutate(.,mean=rowMeans(s_name_bac[,-1])) %>% arrange(desc(mean))
mean_s
s_bac<- mean_s %>% filter(mean>0.005)
Sebum<-data.frame(Character="Sebum",Bacteria=s_bac[,1])
Sebum
```

```{r plot}
library(tidyverse)
# devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)
library(ggplot2)
#install.packages("cols4all")
library(cols4all)
#BiocManager::install("dittoSeq")
library(dittoSeq)
```

```{r plot}
#绘制桑基图
c_all<-rbind(Moisture,Gloss,Sebum)
data <- c_all %>% make_long(Character, Bacteria)
data
##'@指定绘图显示顺序
data$node <- factor(data$node, levels = c(unique(c_all$Bacteria),unique(c_all$Character)))
data
```

```{r plot}
C_B<-ggplot(data, aes(x = x, next_x = next_x, node = node, next_node = next_node,
                fill = node, label = node)) +
  #设置
  geom_sankey(flow.fill="#DFDFDF",#连线颜色
              flow.alpha = 0.5, ## 条带透明度
              flow.color="grey60",#连线边框颜色
              #node.fill=dittoColors()[1:36],#节点颜色，[1:36]数值需要根据自己的数据进行修改
              width=0.2) + #node的宽度
  #设置桑基图文字
  geom_sankey_text(size = 2,#文字大小
                   color= "black",#文字颜色
                   hjust=1) + #文字位置，右对齐
  theme_void()+
  #隐藏图例
  theme(legend.position = 'none') 
ggsave("Characte_Bacteria.pdf", plot = C_B, width = 9, height =6, units = "in", dpi = 300)
C_B

```